# Generated by Django 4.2.30 on 2026-10-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='solution_code',
        ),
    ]
