# Generated by Django 4.2.30 on 2026-10-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_codingquestion_solution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
